.github/workflows/ci.yml, .github/workflows/release.yml
> The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287
=> runs-on: ubuntu-latest (Github Actions)

build.gradle
Also, disable GoLand verification step, as that crashes the verifier plugin. The crash seems to be related to json marshalling at the plugin dependency search API.
We should look at re-enabling the verification later. Disabling for now to get the upgrade and a few bugfixes out.
=> Upgrade GoLand

src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarPresentation.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarWidget.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarWidgetFactory.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
- If the project does not have Hermit installed, show nothing.
- If the project has Hermit, but the plugin is not enabled, show "Hermit disabled"
- If the project has Hermit, and the plugin is enabled, show "Hermit enabled"
Clicking the "Hermit disabled" status re-shows the dialog to enable Hermit for the project.
When enabled:
When disabled:
=> Show the status of the Hermit plugin in the status bar.

src/main/resources/META-INF/plugin.xml
This is what they look like right now in the action menu:
"Yes" could be "Enable Hermit", "No" could be "Don't Enable Hermit."
(tbh I wish for "Disable Hermit" but hey I won't let that stop this PR)
=> Give Hermit actions context

.github/workflows/ci.yml, .github/workflows/release.yml, build.gradle, src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/ProjectExtensions.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarPresentation.kt, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Adds a new status "Hermit failed" if the `hermit install` execution fails. Clicking the status retries the command.
This should make it easier to debug issues, and means the user does not need to close and re-open the project if they are, for example, offline when hermit tries to download the packages for the first time.
Implements https://github.com/cashapp/hermit-ij-plugin/issues/29
Also, fixes how tests are run in CI
=> Show Hermit status as failed if the binary execution failed

src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/HermitVFSChangeListener.kt, src/main/kotlin/com/squareup/cash/hermit/gradle/GradleConfigUpdater.kt
Previously, any change to the `bin/` directory would cause a Hermit refresh. Now, only update if a package symlink or a Hermit script file has changed.
Additionally, fixes a bug where any Hermit refresh would notify on Gradle version. Now, only show the notification when Gradle version actually changes.
=> Only refresh on hermit file changes

src/main/kotlin/com/squareup/cash/hermit/HermitVFSChangeListener.kt, src/test/kotlin/com/squareup/cash/hermit/HermitProjectTestCase.kt, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Previously we were only detecting file changes under the bin dir, but if the bin dir is created in single VFS update, we only get the topmost update.
Also fixes the integration test testing this.
=> Correctly detect `bin` dir creation.

src/main/kotlin/com/squareup/cash/hermit/goland/GoSdkExtensions.kt, src/main/kotlin/com/squareup/cash/hermit/goland/HermitGoEnvUpdater.kt, src/main/kotlin/com/squareup/cash/hermit/idea/HermitJdkUpdater.kt, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Previously, if an existing JDK had been created with a given name, its path was not updated even if the underlying Hermit package changed
=> Handle Channel updates properly

src/main/kotlin/com/squareup/cash/hermit/ProjectExtensions.kt, src/main/kotlin/com/squareup/cash/hermit/idea/HermitJdkUpdater.kt, src/main/kotlin/com/squareup/cash/hermit/idea/JdkExtensions.kt, src/test/kotlin/com/squareup/cash/hermit/FakeHermit.kt, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Uses 
```
JavaSdk.getInstance().createJdk
```
To create the new SDKs instead of manually instantiating the `ProjectJDKImpl`. This detects automatically the JDK version from the JDK dir. Previously on channels, the version was not set correctly.
Also, fixes an issue where if running the IDE from a Hermit environment, that environment could override the versions of detected packages.
Adds an integration test using real hermit to install packages.
=> Correctly set JDK versions for channels

.github/workflows/ci.yml, build.gradle
older versions no longer work with `runIde` task on newer IJ releases
=> Update gradle plugin to 1.5.3

src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/ProjectExtensions.kt, src/main/kotlin/com/squareup/cash/hermit/UI.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarPresentation.kt, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Fixes https://github.com/cashapp/hermit-ij-plugin/issues/37
* This is using reflection, as the API is not available publicly yet.
* When we load the project, we check if it was trusted, and if so, we enable Hermit directly.
* Otherwise, we disable Hermit, and If the user clicked the status bar entry, we will show the message below.
* Clicking `More Information` will take you to https://www.jetbrains.com/help/idea/project-security.html
1. I tested this on the earliest version I see (`2021.1.3` released on `2021/06/28` almost a year ago). But it still has the API, so I'm not sure how it would behave on much older versions that don't have it. Regardless, the entire call is wrapped in a `try / catch`, as we should change the user flow if reflection fails for any reason.
2. In the current …
=> check if project is trusted before enabling

build.gradle, src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/gradle/HermitGradleExecutionAware.kt, src/main/kotlin/com/squareup/cash/hermit/ui/statusbar/HermitStatusBarPresentation.kt, src/main/resources/META-INF/gradle.xml
This prevents errors of Invalid JDK when a user opens a project referring to a hermit managed JDK that is not on disk yet.
This also adds a new hermit status: installing
Closes https://github.com/cashapp/hermit-ij-plugin/issues/33
`GradleExecutionAware`s are run in a single thread sequentially. So, we can just register one before the main initialiser that verifies the Gradle JVM, and pause the thread until Hermit has finished running.
This API was only introduced in `2021.2.1` release released on 7/2021. So, unfortunately, we must drop updates to older IntelliJ versions to enable this.
=> Pause Gradle initialisation until Hermit has installed all packages.

src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/HermitDynamicPluginListener.kt
Fixes an error that can occur if you close the project before Hermit has finished installing.
Also cleans up some minor warnings.
Stacktrace:
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager because container is already disposed (container=Project(name=[redacted], containerState=DISPOSE_COMPLETED, componentStore=[redacted]) (disposed))
at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:686)
at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:659)
at …
```
=> Only update the UI after install if the project is not disposed

build.gradle, src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/com/squareup/cash/hermit/PluginIntegrationTest.kt
Support for 231
This required a new version of `org.jetbrains.intellij` and kotlin, and some related fixes.
Also, statusbar widget XML configuration now requires the factory ID as `id = ` attribute, otherwise the statusbar is hidden.
Finally, after this update, ExtensionPointName.create was not found on all versions anymore. Changed that do a direct constructor call.
=> major version upgrade

build.gradle.kts, gradle.properties, upgrade-major-versions.sh
Because the plugin version may not match the IU release version.
Also reverts change to major version check since the new one doesn't work.
=> fix: get go plugin version separately

build.gradle.kts
So that main doesn't try to upload the same version for each product type.
=> fix: add suffix to non-release versions

build.gradle.kts, gradle.properties
~~LATEST-EAP-SNAPSHOT was set to the stable release, causing the EAP build to fail.~~ LATEST-EAP-SNAPSHOT was set to a version incompatible with the currently-set snapshot version. Switching from LATEST to a major-version one will help catch this problem in the future, but we might have to reconsider upgrading major versions since the failure here is that 232.8* wasn't compatible with 232.7*.
=> fix: use major version EAP snapshot when building EAP

build.gradle.kts, src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/HermitVFSChangeListener.kt
There was a compatibility problem tagged with ProjectLocator.
Iterating through all open projects seems a bit more expensive, but we're not doing a lot per iteration.
=> fix: replace use of ProjectLocator with project access

README.md, src/main/kotlin/com/squareup/cash/hermit/Hermit.kt, src/main/kotlin/com/squareup/cash/hermit/ProjectExtensions.kt
This should make Gradle execution only happen after the Gradle configurer is done.
Also includes chore commits to recognise corretto as a JDK, and to document running locally
=> fix: delay setting state to enabled until all property handlers are done

build.gradle.kts, src/main/resources/META-INF/plugin.xml, src/main/resources/META-INF/properties.xml
looks like the 2023.3 eap needs it: https://youtrack.jetbrains.com/issue/IDEA-333586/Exception-Trying-to-add-extensions-to-non-registered-file-type-Properties-Plugin-com.intellij.java-in-tests
=> fix: add dep on properties plugin

gradle.properties, src/main/kotlin/com/squareup/cash/hermit/HermitVFSChangeListener.kt
It seems that as we were binding the project listeners without project constructors, all of them were triggered for all file events. This meant that if there was a change to Hermit environment, we would get "hermit install" executed as many times as there were open windows.
=> fix: do not run "hermit install" multiple times on a change if multiple windows are open

src/main/kotlin/com/squareup/cash/hermit/Hermit.kt
We've observed hermit not activating on projects where it should.  (specifically an internal Bazel project)
The problem appears to be in resolving the bin directory properly.  (`guessProjectDir` seems to be returning a directory other than the repository root)
This change outputs where it was trying to find hermit when it decided it wasn't a hermit project.
eg for a problematic project java, outputs:
```
java: no hermit detected for java (hermit not found in bin directory under /Users/<userid>/Development/java/.ijwb)
```
=> chore: include extra diagnostics when hermit decides not to activate
